import { Router } from 'express';
import { pool, query } from '../db.js';
import { requireAuth } from '../middleware/auth.js';
import { HttpError } from '../utils/http.js';
const router=Router(); router.use(requireAuth);
router.get('/',async(req,res,next)=>{try{const limit=Math.min(Number(req.query.limit??50),200); const r=await query(`select id,occurred_at,type,program_code,amount,asset,status,reference,tx_hash,description from ledger_transactions where user_id=$1 order by occurred_at desc limit $2`,[req.auth!.userId,limit]);res.json({transactions:r.rows});}catch(e){next(e)}});
router.get('/withdrawals',async(req,res,next)=>{try{const limit=Math.min(Math.max(Number(req.query.limit??20),1),100);const r=await query(`select id,amount,asset,destination_address,status,tx_hash,rejection_reason,created_at,updated_at from withdrawal_requests where user_id=$1 order by created_at desc limit $2`,[req.auth!.userId,limit]);res.json({withdrawals:r.rows});}catch(e){next(e)}});router.get('/withdrawals/:id',async(req,res,next)=>{try{const r=await query(`select id,amount,asset,destination_address,status,tx_hash,rejection_reason,created_at,updated_at from withdrawal_requests where id=$1 and user_id=$2`,[req.params.id,req.auth!.userId]);if(!r.rowCount)throw new HttpError(404,'Withdrawal not found');res.json({withdrawal:r.rows[0]});}catch(e){next(e)}});
router.post('/withdrawals',async(req,res,next)=>{try{const amount=String(req.body?.amount??'').trim();const address=String(req.body?.address??'').trim();if(!/^(?:0|[1-9]\d*)(?:\.\d{1,8})?$/.test(amount)||Number(amount)<=0)throw new HttpError(400,'Valid positive amount required'); if(!/^0x[a-fA-F0-9]{40}$/.test(address))throw new HttpError(400,'Valid EVM destination address required'); const client=await pool.connect(); try { await client.query('begin'); await client.query(`select id from app_users where id=$1 for update`,[req.auth!.userId]); const asset=process.env.PRIMARY_ASSET??'USDT'; const balance=await client.query<{available:string}>(`select (coalesce(sum(case when type='earned' and status='completed' then amount else 0 end),0)-coalesce(sum(case when type='withdrawal' and status in ('pending','completed') then amount else 0 end),0))::text as available from ledger_transactions where user_id=$1 and asset=$2`,[req.auth!.userId,asset]); const available=balance.rows[0]?.available??'0'; const sufficient=(await client.query<{ok:boolean}>(`select $1::numeric >= $2::numeric as ok`,[available,amount])).rows[0]?.ok; if(!sufficient) throw new HttpError(409,'Insufficient available balance'); const r=await client.query(`insert into withdrawal_requests(user_id,amount,asset,destination_address,status) values($1,$2,$3,$4,'pending') returning id,amount,asset,destination_address,status,created_at,updated_at`,[req.auth!.userId,amount,asset,address]); await client.query(`insert into ledger_transactions(user_id,type,amount,asset,status,reference,description,metadata) values($1,'withdrawal',$2,$3,'pending',$4,$5,$6::jsonb)`,[req.auth!.userId,amount,asset,`withdrawal:${r.rows[0].id}`,'Withdrawal amount reserved pending payout',JSON.stringify({withdrawalId:r.rows[0].id,destinationAddress:address})]); await client.query(`insert into audit_logs(actor_user_id,action,entity_type,entity_id,metadata) values($1,'withdrawal_requested','withdrawal_request',$2,$3)`,[req.auth!.userId,r.rows[0].id,JSON.stringify({amount,asset:process.env.PRIMARY_ASSET??'USDT'})]); await client.query('commit'); res.status(201).json({withdrawal:r.rows[0]}); } catch (e) { await client.query('rollback').catch(()=>{}); throw e; } finally { client.release(); }}catch(e){next(e)}});
export default router;
