import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';

const html = readFileSync(resolve(process.cwd(), 'index.html'), 'utf8');
assert.equal((html.match(/<style\b/gi) ?? []).length, 1);
assert.equal((html.match(/<\/style>/gi) ?? []).length, 1);
assert.match(html, /<div class="splash-logo"><img src="\/zenit-logo\.png\?zenit-official-20260928"/);
assert.match(html, /minimum=1800/);
assert.match(html, /maximum=4200/);
assert.match(html, /zenit:splash-ready/);
assert.doesNotMatch(html, /SPLASH_DURATION\s*=\s*8000/);
assert.doesNotMatch(html, /setTimeout\(releaseSplash/);
assert.match(html, /@media \(max-width:820px\)[\s\S]*?\.onboard-art \{\s*display:flex;/);

assert.equal((html.match(/function openReturningLogin\(\)/g) ?? []).length, 1);
assert.match(html, /window\.zenitOpenReturningLogin=openReturningLogin;/);
assert.match(html, /window\.zenitOpenExistingLogin=\(\)=>openReturningLogin\(\);/);
assert.match(html, /<form id="registrationForm" novalidate>/);
assert.match(html, /<button type="submit"[^>]*id="registrationSubmit"[^>]*data-action="registration-submit"/);
assert.match(html, /getElementById\("registrationForm"\)\?\.addEventListener\("submit",event=>\{\s*event\.preventDefault\(\);\s*void requestRegistration\(\);\s*\}\)/);
assert.doesNotMatch(html, /registrationWhatsappReminderShown|showRegistrationWhatsAppReminder/);
assert.match(html, /CONNECT WALLET <span>→<\/span><\/button>/);
assert.match(html, /const openWallet=window\.zenitOpenWallet;if\(typeof openWallet!=="function"\)\{toast\("Wallet is still loading"/);
const pickerFunctionPos = html.indexOf('function bindWhatsAppPicker(');
const pickerBindingPos = html.indexOf('bindWhatsAppPicker("#registrationWhatsappCountry"');
assert.ok(pickerFunctionPos >= 0 && pickerBindingPos > pickerFunctionPos, "WhatsApp picker must bind only after its country data/functions are initialized");
assert.match(html, /function countryFlagUrl\(iso\)/);
assert.match(html, /class="whatsapp-flag-image"/);
assert.doesNotMatch(html, /if\(action==="registration-submit"\)/);
assert.match(html, /function internationalWhatsAppValid\(value\)/);
assert.match(html, /function composeWhatsAppNumber\(selectId,inputId\)/);
assert.match(html, /https:\/\/flagcdn\.com\/w40\/pk\.png/);
assert.match(html, /\.modal-backdrop \{ position: fixed; z-index: 110;/);
assert.doesNotMatch(html, /event\.stopImmediatePropagation\(\);openReturningLogin\(\);return;/);

console.log('✓ onboarding login wiring regression checks passed');
const walletBridge = readFileSync(resolve(process.cwd(), 'src/wallet-bridge.ts'), 'utf8');
assert.match(html, /id="onboardExistingLogin"[^>]*data-action="existing-wallet-login"/);
assert.match(html, /if\(action==="existing-wallet-login"\)\{localStorage\.setItem\("zenitAuthMode","existing"\);const openReturning=window\.zenitOpenReturningLogin/);
assert.doesNotMatch(html, /fetch\(api\s*\+\s*["']\/api\/auth\/webauthn/);
assert.match(html, /backendBase\(\)\+["']\/api\/auth\/webauthn\/login\/options/);
assert.match(html, /backendBase\(\)\+["']\/api\/auth\/webauthn\/login\/verify/);
assert.match(html, /requestAnimationFrame\(\(\)=>backdrop\.classList\.add\(["']open["']\)\)/);
assert.match(walletBridge, /await kit\.open\(\)/);
assert.match(walletBridge, /zenit:wallet-ready/);

assert.doesNotMatch(html, /params\.delete\("wallet_handoff"\);/);
assert.doesNotMatch(html, /params\.delete\("email_verified"\);/);
assert.match(html, /localStorage\.setItem\("zenitWalletHandoffToken",data\.walletHandoffToken\)/);
assert.match(html, /localStorage\.setItem\("zenitAuthMode","onboarding"\)/);

assert.match(html, /grid-template-columns:1fr;\s*grid-template-rows:minmax\(250px,42dvh\)/);
assert.match(html, /@media \(max-width:820px\)/);
assert.match(html, /window\.__zenitAppReady=true/);
assert.match(html, /zenit:app-ready/);
assert.match(html, /maximum=4200/);
assert.match(walletBridge, /function setWalletButtonsBusy\(busy: boolean\)/);
assert.match(walletBridge, /await kit\.open\(\)/);
assert.doesNotMatch(walletBridge, /await \(appKit as any\)\.open\(\{ view: ['"]Connect['"] \}\)/);

console.log('✓ cross-device onboarding, splash, and wallet-open regression checks passed');

assert.match(html, /if\(typeof openReturning==="function"\)\{openReturning\(\);\}else\{toast\("Login is still loading"/);
assert.doesNotMatch(html, /async function openExistingWalletLogin\(\)\{/);
assert.match(html, /id="connectReturningWallet"/);
assert.match(html, /id="useBiometricLogin"/);
assert.match(html, /\.onboarding \.onboard-actions \.btn[\s\S]*background:linear-gradient\(180deg,#d0ae5b,#a98538\) !important/);
assert.match(html, /\.onboarding \.onboard-existing \.btn[\s\S]*background:linear-gradient\(180deg,#d0ae5b,#a98538\) !important/);
assert.match(html, /navigator\.credentials\.get\(\{[\s\S]*publicKey:\{[\s\S]*challenge:bytes\(opt\.challenge\)[\s\S]*rpId:opt\.rpId[\s\S]*userVerification:"required"[\s\S]*timeout:60000/);
assert.match(html, /Phone biometric verified\. Opening your dashboard/);
assert.match(html, /window\.startApp=startApp/);
assert.match(html, /id="skipOptionalPin"/);
assert.match(html, /SKIP FOR NOW · OPEN DASHBOARD/);
assert.match(html, /id="skipBiometric"/);
assert.match(html, /closeBiometricPrompt/);
assert.match(html, /data-action="enable-biometric"/);
assert.match(html, /window\.zenitEnrollBiometric=async/);
assert.match(html, /OPTIONAL SIGN-IN SECURITY/);
assert.match(html, /PIN and device passkeys are optional sign-in options/);
assert.match(html, /await window\.zenitLoadBackend\?\.\(data\.token\)/);
assert.match(walletBridge, /if \(\(data\.pinRequired \|\| data\.pinSetupRequired\) && data\.challengeId && !data\.token\)/);
assert.doesNotMatch(walletBridge, /if \(localStorage\.getItem\('zenitPinChallenge'\)\) return/);
assert.match(walletBridge, /window\.dispatchEvent\(new CustomEvent\('zenit:authenticated', \{ detail: data\.user \|\| \{\} \}\)\)/);
const authSource = readFileSync(resolve(process.cwd(), '../backend/src/routes/auth.ts'), 'utf8');
assert.match(authSource, /let pinChallengeId: string \| undefined;/);
assert.match(authSource, /\.\.\.\(pinChallengeId \? \{ pinRequired:!!user\.pin_hash, pinSetupRequired:!user\.pin_hash, challengeId:pinChallengeId \} : \{\}\)/);
console.log('✓ optional PIN/passkey controls and wallet-to-dashboard contract are wired');

assert.match(html, /data-action="test-push"/);
assert.match(html, /backendFetch\(['"]\/api\/me\/push\/test['"]/);
console.log('✓ authenticated push self-test is wired without touching financial flows');
